### ISSUE TITLE
[MOBFDevice duid] crash with [NSObject iskinkdofClass]

### ISSUE THREAD

**Issue by tpctt** [MobClub/ShareSDK-for-iOS#11]
[MOBFDevice duid] crash with [NSObject iskinkdofClass].
1. There is two report with ios9.3 and ios10.0,
2. SDK is latest at a month ago.
3. xcode 8.1 with OS X 10.11.6
4. good luck for you

**Comment by vhbvb** [comment]
最新版本已修复
