### ISSUE TITLE
Error Domain=NSPOSIXErrorDomain Code=13

### ISSUE THREAD

**Issue by wakaryry** [MobClub/ShareSDK-for-iOS#26]
> [NetworkInfo] Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x281d90e40, domain=1, instance=1>

这个错误应该是ShareSDK抛出的吧。我在没有加入这个之前，没有这个错误。

**Comment by vhbvb** [comment]
这个不属于sharesdk的业务，为系统网络错误抛出

**Comment by cocoaroger** [comment]
这难道是apple的bug

**Comment by vhbvb** [comment]
有影响正常的业务么。？如果有的话 可以加我们技术支持qq:4006852216 详细描述下问题 ~~~

**Comment by cocoaroger** [comment]
没影响，只是xcode10.1会出现，更新了ShareSDK到最新版后就不出现了

**Comment by vhbvb** [comment]
好的，如果还有其他问题的话可以官方论坛给我们留言或者咨询我们的 技术支持QQ，有专人对接的 ~

**Comment by ZhouShisong** [comment]
这个报错不知道有什么影响

**Comment by guominfang** [comment]
我也有这个问题，怎么解决？

**Comment by wakaryry** [comment]
可能是与苹果有关的吧。暂时不影响。
