### ISSUE TITLE
NSErrorFailingURLStringKey=http://api.share.mob.com:80/log4

### ISSUE THREAD

**Issue by wakaryry** [MobClub/ShareSDK-for-iOS#27]
NSErrorFailingURLStringKey=http://api.share.mob.com:80/log4, NSErrorFailingURLKey=http://api.share.mob.com:80/log4, _kCFStreamErrorDomainKey=1} [-1001]
TIC Read Status [14:0x281914600]: 1:60
HTTP load failed (error code: -1001 [1:60])
finished with error - code: -1001
load failed with error Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=60, NSUnderlyingError=0x28228d650 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x280f3c820 [0x25e6455f0]>{length = 16, capacity = 16, bytes = 0x100200500e11612d0000000000000000}, _kCFStreamErrorCodeKey=60, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <C5D8333B-C237-47CF-B0BA-30825DCEB302>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <C5D8333B-C237-47CF-B0BA-30825DCEB302>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=http://api.share.mob.com:80/log4, NSErrorFailingURLKey=http://api.share.mob.com:80/log4, _kCFStreamErrorDomainKey=1} [-1001]
 Could not load IOSurface for time string. Rendering locally instead.

**Comment by vhbvb** [comment]
这个是我们的日志服务，不影响业务的。。可以不理会

**Comment by seekcx** [comment]
能把这个关闭吗，太影响我看日志了。
