### ISSUE TITLE
pod install 报警告 http

### ISSUE THREAD

**Issue by acerpeanut** [MobClub/ShareSDK-for-iOS#29]
[!] 'mob_sharesdk' uses the unencrypted 'http' protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts. Otherwise, please reach out to the library author to notify them of this security issue.

**Comment by wukexiu** [comment]
此问题并不影响使用，在tag-4.2.3之后source已经使用https，已经解决，不会出现此警告
