### ISSUE TITLE
微信授权后返回的信息是英文的-如何指定返回的信息为中文

### ISSUE THREAD

**Issue by jonny77** [MobClub/ShareSDK-for-iOS#30]
如题

**Comment by jonny77** [comment]
![微信截图_20190327201050](https://user-images.githubusercontent.com/1962170/55074880-72bc3c00-50cc-11e9-83f0-b681fd8a9866.png)

**Comment by wukexiu** [comment]
此问题将在下一个版本修复，如有急需可联系技术支持获取修复的私包

**Comment by bingolib** [comment]
> 此问题将在下一个版本修复，如有急需可联系技术支持获取修复的私包，用户使用：#import <WechatConnector / WechatConnector.h> [WeChatConnector setLang：@“ zh_CN”]；

你好 此功能可正常使用了吗？我设置后无效呢
